/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta webhook verification */
        get: operations["meta_verify_webhooks_meta_get"];
        put?: never;
        /** Meta webhook receiver */
        post: operations["meta_receive_webhooks_meta_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/aisensy/{channel_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AiSensy project webhook receiver */
        post: operations["aisensy_receive_webhooks_aisensy__channel_token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_v1_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_v1_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_v1_clients__client_id__get"];
        put?: never;
        post?: never;
        /** Delete Client */
        delete: operations["delete_client_api_v1_clients__client_id__delete"];
        options?: never;
        head?: never;
        /** Update Client */
        patch: operations["update_client_api_v1_clients__client_id__patch"];
        trace?: never;
    };
    "/api/v1/clients/{client_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge */
        get: operations["get_knowledge_api_v1_clients__client_id__knowledge_get"];
        /** Put Knowledge */
        put: operations["put_knowledge_api_v1_clients__client_id__knowledge_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/knowledge/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Knowledge */
        post: operations["approve_knowledge_api_v1_clients__client_id__knowledge_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/knowledge/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_v1_clients__client_id__knowledge_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/knowledge/restore/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Version */
        post: operations["restore_version_api_v1_clients__client_id__knowledge_restore__version__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/knowledge/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Knowledge
         * @description The full system prompt as plain text, for pasting into other platforms.
         */
        get: operations["export_knowledge_api_v1_clients__client_id__knowledge_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/templates/{niche}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_api_v1_knowledge_templates__niche__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel */
        get: operations["get_channel_api_v1_clients__client_id__channel_get"];
        /** Put Channel */
        put: operations["put_channel_api_v1_clients__client_id__channel_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/channel/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Channel
         * @description Send 'Bot Desk test message ✅' to the owner's phone and return the provider response.
         */
        post: operations["test_channel_api_v1_clients__client_id__channel_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/test-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Chat
         * @description Same AI engine and guardrails as live WhatsApp. Nothing is saved or sent.
         */
        post: operations["test_chat_api_v1_clients__client_id__test_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inbox
         * @description Contacts sorted by last message, with unread count and a preview of the last message.
         */
        get: operations["inbox_api_v1_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contact */
        get: operations["get_contact_api_v1_contacts__contact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contact Messages
         * @description Oldest-to-newest page of messages. Without `before`, returns the latest page and marks it read.
         */
        get: operations["contact_messages_api_v1_contacts__contact_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reply
         * @description Send a message as a human agent. Only allowed inside WhatsApp's 24-hour customer-care window.
         */
        post: operations["reply_api_v1_contacts__contact_id__reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Handoff */
        post: operations["set_handoff_api_v1_contacts__contact_id__handoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/opt-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Opt Out */
        post: operations["set_opt_out_api_v1_contacts__contact_id__opt_out_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_api_v1_leads_get"];
        put?: never;
        /** Create Lead */
        post: operations["create_lead_api_v1_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Lead */
        patch: operations["update_lead_api_v1_leads__lead_id__patch"];
        trace?: never;
    };
    "/api/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Payments */
        get: operations["list_payments_api_v1_payments_get"];
        put?: never;
        /** Create Payment */
        post: operations["create_payment_api_v1_payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Payment */
        delete: operations["delete_payment_api_v1_payments__payment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/renewals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Renewals */
        get: operations["renewals_api_v1_billing_renewals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/attention/{item_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Attention */
        post: operations["resolve_attention_api_v1_dashboard_attention__item_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_v1_reports_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveIn */
        ApproveIn: {
            /** Approved By Name */
            approved_by_name: string;
        };
        /** AttentionOut */
        AttentionOut: {
            /** Id */
            id?: string | null;
            /** Client Id */
            client_id: string | null;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
        };
        /** ChannelIn */
        ChannelIn: {
            /** Display Phone */
            display_phone?: string | null;
            /** Meta Phone Number Id */
            meta_phone_number_id?: string | null;
            /** Meta Waba Id */
            meta_waba_id?: string | null;
            /**
             * Meta Access Token
             * @description Write-only. Send '' to clear.
             */
            meta_access_token?: string | null;
            /** Aisensy Project Id */
            aisensy_project_id?: string | null;
            /**
             * Aisensy Api Key
             * @description Write-only AiSensy Project API password
             */
            aisensy_api_key?: string | null;
            /**
             * Aisensy Webhook Secret
             * @description Write-only; used to verify signatures
             */
            aisensy_webhook_secret?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /**
             * Rotate Channel Token
             * @default false
             */
            rotate_channel_token: boolean;
        };
        /** ChannelOut */
        ChannelOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            provider: components["schemas"]["Provider"];
            effective_provider: components["schemas"]["Provider"];
            /** Display Phone */
            display_phone: string | null;
            /** Meta Phone Number Id */
            meta_phone_number_id: string | null;
            /** Meta Waba Id */
            meta_waba_id: string | null;
            meta_access_token: components["schemas"]["SecretHint"];
            /** Aisensy Project Id */
            aisensy_project_id: string | null;
            aisensy_api_key: components["schemas"]["SecretHint"];
            aisensy_webhook_secret: components["schemas"]["SecretHint"];
            /** Is Active */
            is_active: boolean;
            /** Last Inbound At */
            last_inbound_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Webhook Url */
            webhook_url: string;
            /** Meta Verify Token Set */
            meta_verify_token_set: boolean;
        };
        /** ChannelTestOut */
        ChannelTestOut: {
            /** Ok */
            ok: boolean;
            /** Provider */
            provider: string;
            /** To */
            to: string;
            /** Provider Message Id */
            provider_message_id: string | null;
            /** Status Code */
            status_code: number | null;
            /** Error */
            error: string | null;
            /** Response */
            response: {
                [key: string]: unknown;
            } | null;
        };
        /** ChatTurn */
        ChatTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Name */
            name: string;
            /** @default other */
            niche: components["schemas"]["Niche"];
            /**
             * City
             * @default
             */
            city: string;
            /**
             * Owner Name
             * @default
             */
            owner_name: string;
            /**
             * Owner Phone
             * @description E.164, e.g. +919840012345
             */
            owner_phone?: string | null;
            /** @default lead */
            status: components["schemas"]["ClientStatus"];
            /** @default starter */
            package: components["schemas"]["Package"];
            /** Trial Start */
            trial_start?: string | null;
            /** Live Date */
            live_date?: string | null;
            /** Languages */
            languages?: string[];
            provider_override?: components["schemas"]["Provider"] | null;
            /**
             * Bot Enabled
             * @default true
             */
            bot_enabled: boolean;
            /** Notes */
            notes?: string | null;
            /**
             * Setup Fee
             * @description Defaults from the package when omitted
             */
            setup_fee?: number | string | null;
            /**
             * Monthly Fee
             * @description Defaults from the package when omitted
             */
            monthly_fee?: number | string | null;
        };
        /** ClientOut */
        ClientOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            niche: components["schemas"]["Niche"];
            /** City */
            city: string;
            /** Owner Name */
            owner_name: string;
            /** Owner Phone */
            owner_phone: string | null;
            status: components["schemas"]["ClientStatus"];
            package: components["schemas"]["Package"];
            /** Setup Fee */
            setup_fee: string;
            /** Monthly Fee */
            monthly_fee: string;
            /** Trial Start */
            trial_start: string | null;
            /** Live Date */
            live_date: string | null;
            /** Languages */
            languages: string[];
            provider_override: components["schemas"]["Provider"] | null;
            /** Bot Enabled */
            bot_enabled: boolean;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            effective_provider: components["schemas"]["Provider"];
            /** Billing Status */
            billing_status?: string | null;
            /** Next Due Date */
            next_due_date?: string | null;
            /** Setup Paid */
            setup_paid?: boolean | null;
        };
        /**
         * ClientStatus
         * @enum {string}
         */
        ClientStatus: "lead" | "trial" | "live" | "paused";
        /** ClientUpdate */
        ClientUpdate: {
            /** Name */
            name?: string | null;
            niche?: components["schemas"]["Niche"] | null;
            /** City */
            city?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Owner Phone */
            owner_phone?: string | null;
            status?: components["schemas"]["ClientStatus"] | null;
            package?: components["schemas"]["Package"] | null;
            /** Setup Fee */
            setup_fee?: number | string | null;
            /** Monthly Fee */
            monthly_fee?: number | string | null;
            /** Trial Start */
            trial_start?: string | null;
            /** Live Date */
            live_date?: string | null;
            /** Languages */
            languages?: string[] | null;
            provider_override?: components["schemas"]["Provider"] | null;
            /** Bot Enabled */
            bot_enabled?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** ConfigOut */
        ConfigOut: {
            /** Default Provider */
            default_provider: string;
            /** Ai Model */
            ai_model: string;
            /** Ai Fallback Model */
            ai_fallback_model: string;
            /** Packages */
            packages: {
                [key: string]: components["schemas"]["PackageInfo"];
            };
            /** Languages */
            languages: string[];
            /** Niches */
            niches: string[];
            /** Trial Days */
            trial_days: number;
            /** App Version */
            app_version: string;
        };
        /** ContactOut */
        ContactOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Wa Id */
            wa_id: string;
            /** Profile Name */
            profile_name: string | null;
            /** Detected Language */
            detected_language: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Last Inbound At */
            last_inbound_at: string | null;
            /** Handoff Active */
            handoff_active: boolean;
            /** Handoff Since */
            handoff_since: string | null;
            /** Handoff Reason */
            handoff_reason: string | null;
            /** Opted Out */
            opted_out: boolean;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Paying Clients */
            paying_clients: number;
            /** Goal */
            goal: number;
            /** Mrr */
            mrr: string;
            /** Collected This Month */
            collected_this_month: string;
            /** Overdue Amount */
            overdue_amount: string;
            /** Overdue Count */
            overdue_count: number;
            /** Trials Ending 7D */
            trials_ending_7d: number;
            /** Leads New 7D */
            leads_new_7d: number;
            /** Handoffs Open */
            handoffs_open: number;
            /** Messages 7D */
            messages_7d: number;
            /** Ai Cost Inr 30D */
            ai_cost_inr_30d: string;
            /** Pipeline */
            pipeline: {
                [key: string]: number;
            };
            /** Attention */
            attention: components["schemas"]["AttentionOut"][];
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "in" | "out";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandoffIn */
        HandoffIn: {
            /** Active */
            active: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Db */
            db: boolean;
            /** Default Provider */
            default_provider: string;
        };
        /** InboxItem */
        InboxItem: {
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Client Name */
            client_name: string;
            /** Wa Id */
            wa_id: string;
            /** Profile Name */
            profile_name: string | null;
            /** Detected Language */
            detected_language: string | null;
            /** Handoff Active */
            handoff_active: boolean;
            /** Handoff Reason */
            handoff_reason: string | null;
            /** Opted Out */
            opted_out: boolean;
            /** Last Inbound At */
            last_inbound_at: string | null;
            /**
             * Can Reply
             * @description True if the customer wrote within the last 24 hours
             */
            can_reply: boolean;
            /** Unread Count */
            unread_count: number;
            /**
             * Last Message At
             * Format: date-time
             */
            last_message_at: string;
            /** Last Message Preview */
            last_message_preview: string | null;
            last_message_sender: components["schemas"]["Sender"];
        };
        /** KnowledgeIn */
        KnowledgeIn: {
            /** Address */
            address?: string | null;
            /** Timings */
            timings?: string | null;
            /**
             * Services
             * @description One service per line, with ₹ prices
             */
            services?: string | null;
            /** Faqs */
            faqs?: string | null;
            /** Booking Instructions */
            booking_instructions?: string | null;
            /**
             * Rules
             * @description Never-say topics and hand-over topics
             */
            rules?: string | null;
            /** Handoff Contact */
            handoff_contact?: string | null;
            /** Tone */
            tone?: string | null;
            /**
             * Note
             * @description Optional note stored with this version
             */
            note?: string | null;
        };
        /** KnowledgeOut */
        KnowledgeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Address */
            address: string;
            /** Timings */
            timings: string;
            /** Services */
            services: string;
            /** Faqs */
            faqs: string;
            /** Booking Instructions */
            booking_instructions: string;
            /** Rules */
            rules: string;
            /** Handoff Contact */
            handoff_contact: string;
            /** Tone */
            tone: string;
            /** Approved */
            approved: boolean;
            /** Approved At */
            approved_at: string | null;
            /** Approved By Name */
            approved_by_name: string | null;
            /** Version */
            version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** KnowledgeTemplateOut */
        KnowledgeTemplateOut: {
            /** Niche */
            niche: string;
            /** Sample Business */
            sample_business: string;
            /** Label */
            label: string;
            /** Knowledge */
            knowledge: {
                [key: string]: string;
            };
        };
        /** KnowledgeVersionOut */
        KnowledgeVersionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /** Content */
            content: {
                [key: string]: string;
            };
            /** Saved By */
            saved_by: string | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LeadCreate */
        LeadCreate: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Contact Id */
            contact_id?: string | null;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Need
             * @default
             */
            need: string;
            /**
             * Preferred Time
             * @default
             */
            preferred_time: string;
            /** @default new */
            status: components["schemas"]["LeadStatus"];
            /** Notes */
            notes?: string | null;
        };
        /** LeadInfo */
        LeadInfo: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Need
             * @default
             */
            need: string;
            /**
             * When
             * @default
             */
            when: string;
        };
        /** LeadOut */
        LeadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Contact Id */
            contact_id: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Need */
            need: string;
            /** Preferred Time */
            preferred_time: string;
            status: components["schemas"]["LeadStatus"];
            /** Source Message Id */
            source_message_id: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LeadStatus
         * @enum {string}
         */
        LeadStatus: "new" | "contacted" | "won" | "lost";
        /** LeadUpdate */
        LeadUpdate: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Need */
            need?: string | null;
            /** Preferred Time */
            preferred_time?: string | null;
            status?: components["schemas"]["LeadStatus"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            direction: components["schemas"]["Direction"];
            sender: components["schemas"]["Sender"];
            msg_type: components["schemas"]["MsgType"];
            /** Body */
            body: string | null;
            status: components["schemas"]["MsgStatus"];
            /** Error */
            error: string | null;
            /** Ai Model */
            ai_model: string | null;
            /** Tokens In */
            tokens_in: number | null;
            /** Tokens Out */
            tokens_out: number | null;
            /** Cost Usd */
            cost_usd: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Meta */
            meta: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MonthlyReportOut */
        MonthlyReportOut: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Month */
            month: string;
            /** Chats */
            chats: number;
            /** Messages In */
            messages_in: number;
            /** Messages Out */
            messages_out: number;
            /** Bot Replies */
            bot_replies: number;
            /** Agent Replies */
            agent_replies: number;
            /** Leads */
            leads: number;
            /** Handoffs */
            handoffs: number;
            /** Night Enquiries */
            night_enquiries: number;
            /** Night Share */
            night_share: number;
            /** Top Questions */
            top_questions: components["schemas"]["QuestionCount"][];
            /** Languages */
            languages: {
                [key: string]: number;
            };
            /** Avg Bot Reply Seconds */
            avg_bot_reply_seconds: number | null;
            /** Ai Cost Inr */
            ai_cost_inr: string;
        };
        /**
         * MsgStatus
         * @enum {string}
         */
        MsgStatus: "received" | "sent" | "delivered" | "read" | "failed";
        /**
         * MsgType
         * @enum {string}
         */
        MsgType: "text" | "image" | "audio" | "location" | "template" | "other";
        /**
         * Niche
         * @enum {string}
         */
        Niche: "dental_clinic" | "skin_clinic" | "salon" | "coaching_centre" | "gym" | "bakery_sweets" | "real_estate" | "restaurant" | "other";
        /** OkOut */
        OkOut: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** OptOutIn */
        OptOutIn: {
            /** Opted Out */
            opted_out: boolean;
        };
        /**
         * Package
         * @enum {string}
         */
        Package: "starter" | "business" | "growth" | "custom";
        /** PackageInfo */
        PackageInfo: {
            /** Setup */
            setup: string;
            /** Monthly */
            monthly: string;
            /** Includes */
            includes: string[];
        };
        /** Page[ClientOut] */
        Page_ClientOut_: {
            /** Items */
            items: components["schemas"]["ClientOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PaymentCreate */
        PaymentCreate: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            type: components["schemas"]["PaymentType"];
            /** Amount */
            amount: number | string;
            /**
             * For Month
             * @description Monthly payments only; normalised to the 1st
             */
            for_month?: string | null;
            /**
             * Paid On
             * @description Defaults to today (IST)
             */
            paid_on?: string | null;
            /** @default UPI */
            method: components["schemas"]["PaymentMethod"];
            /** Reference */
            reference?: string | null;
            /** Note */
            note?: string | null;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "UPI" | "cash" | "bank" | "card";
        /** PaymentOut */
        PaymentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            type: components["schemas"]["PaymentType"];
            /** Amount */
            amount: string;
            /** For Month */
            for_month: string | null;
            /**
             * Paid On
             * Format: date
             */
            paid_on: string;
            method: components["schemas"]["PaymentMethod"];
            /** Reference */
            reference: string | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PaymentType
         * @enum {string}
         */
        PaymentType: "setup" | "monthly" | "other";
        /**
         * Provider
         * @enum {string}
         */
        Provider: "own" | "aisensy";
        /** QuestionCount */
        QuestionCount: {
            /** Question */
            question: string;
            /** Count */
            count: number;
        };
        /** RenewalOut */
        RenewalOut: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Client Name */
            client_name: string;
            /** Package */
            package: string;
            /** Setup Fee */
            setup_fee: string;
            /** Amount */
            amount: string;
            /** Due Date */
            due_date: string | null;
            /** Status */
            status: string;
            /** Setup Paid */
            setup_paid: boolean;
            /** Period Month */
            period_month?: string | null;
        };
        /** ReplyIn */
        ReplyIn: {
            /** Body */
            body: string;
        };
        /** SecretHint */
        SecretHint: {
            /** Has Token */
            has_token: boolean;
            /** Last4 */
            last4: string | null;
        };
        /**
         * Sender
         * @enum {string}
         */
        Sender: "customer" | "bot" | "agent" | "system";
        /** TestChatIn */
        TestChatIn: {
            /** History */
            history?: components["schemas"]["ChatTurn"][];
            /** Message */
            message: string;
        };
        /** TestChatOut */
        TestChatOut: {
            /** Reply */
            reply: string;
            /** Language */
            language: string;
            lead: components["schemas"]["LeadInfo"] | null;
            /** Handoff */
            handoff: boolean;
            /** Handoff Reason */
            handoff_reason: string | null;
            /** Model */
            model: string | null;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Cost Inr */
            cost_inr: string;
            /** Guardrail Notes */
            guardrail_notes: string[];
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "staff";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebhookAck */
        WebhookAck: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    meta_verify_webhooks_meta_get: {
        parameters: {
            query?: {
                "hub.mode"?: string;
                "hub.verify_token"?: string;
                "hub.challenge"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_receive_webhooks_meta_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
        };
    };
    aisensy_receive_webhooks_aisensy__channel_token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    list_clients_api_v1_clients_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ClientStatus"] | null;
                niche?: components["schemas"]["Niche"] | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ClientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_v1_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_v1_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_api_v1_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_v1_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_api_v1_clients__client_id__knowledge_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_knowledge_api_v1_clients__client_id__knowledge_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_knowledge_api_v1_clients__client_id__knowledge_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_clients__client_id__knowledge_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_version_api_v1_clients__client_id__knowledge_restore__version__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_knowledge_api_v1_clients__client_id__knowledge_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System prompt as plain text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_v1_knowledge_templates__niche__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                niche: components["schemas"]["Niche"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_channel_api_v1_clients__client_id__channel_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_channel_api_v1_clients__client_id__channel_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_channel_api_v1_clients__client_id__channel_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_chat_api_v1_clients__client_id__test_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestChatIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inbox_api_v1_inbox_get: {
        parameters: {
            query?: {
                client_id?: string | null;
                handoff?: boolean | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contact_api_v1_contacts__contact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contact_messages_api_v1_contacts__contact_id__messages_get: {
        parameters: {
            query?: {
                /** @description Return messages older than this timestamp */
                before?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reply_api_v1_contacts__contact_id__reply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_handoff_api_v1_contacts__contact_id__handoff_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_opt_out_api_v1_contacts__contact_id__opt_out_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptOutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leads_api_v1_leads_get: {
        parameters: {
            query?: {
                client_id?: string | null;
                contact_id?: string | null;
                status?: components["schemas"]["LeadStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_api_v1_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lead_api_v1_leads__lead_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_payments_api_v1_payments_get: {
        parameters: {
            query?: {
                client_id?: string | null;
                type?: components["schemas"]["PaymentType"] | null;
                /** @description YYYY-MM: matches for_month, or paid_on for non-monthly */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_payment_api_v1_payments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_payment_api_v1_payments__payment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renewals_api_v1_billing_renewals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenewalOut"][];
                };
            };
        };
    };
    summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    resolve_attention_api_v1_dashboard_attention__item_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_v1_reports_monthly_get: {
        parameters: {
            query: {
                client_id: string;
                /** @description YYYY-MM (IST); defaults to the current month */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
